javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
java -Xmx128M -Xms16M HelloWorld
java -Xmx128M -Xms16M HelloWorld
java -Xmx128M -Xms16M HelloWorld
java -Xmx128M -Xms16M HelloWorld
java -Xmx128M -Xms16M HelloWorld
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
java -Xmx128M -Xms16M HelloWorld
java -Xmx128M -Xms16M HelloWorld
java -Xmx128M -Xms16M HelloWorld
java -Xmx128M -Xms16M Main
java -Xmx128M -Xms16M Main
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
java -Xmx128M -Xms16M Main
java -Xmx128M -Xms16M Main
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
javac Main.java
